apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-svc
spec:
  selector:
    app: ftps
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
      name: ftps-port
    - protocol: TCP
      port: 21000
      targetPort: 21000
      name: pasv-port
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
          - containerPort: 21
          - containerPort: 21000